import Head from "next/head";
import { Inter } from "@next/font/google";
import { useRouter } from "next/router";
import { useEffect } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const router = useRouter();

	const perfromAuth = async () => {
		const res = await axios.get(
			`${process.env.NEXT_PUBLIC_BACKEND_URL}/generateUrl`,
		);
		const { url } = res.data;
		router.push(url);
	};

	useEffect(() => {
		const { code } = router.query;
		if (code) {
			const getAccessToken = async () => {
				const res = await axios.post(
					`${process.env.NEXT_PUBLIC_BACKEND_URL}/getAccessToken`,
					{ code },
				);
				const { accessToken } = res.data;
				const htmlToDocument = async () => {
					const res = await axios.post(
						`${process.env.NEXT_PUBLIC_BACKEND_URL}/getDocument`,
						{
							accessToken,
							documentId: "1MNXS2rkuOMX_mN2iAbaw6PEzPvuYgeITcSyNMbaInkM",
						},
					);
					const { htmlDoc } = res.data;
					console.log(htmlDoc);
				};
				htmlToDocument();
			};
			getAccessToken();
		}
	}, [router.query]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<button onMouseDown={perfromAuth}>Grant Access</button>
			</main>
		</>
	);
}
